repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        language: node
        entry: npx biome check --write
        types_or: [javascript, jsx, ts, tsx, json]
        pass_filenames: true

      - id: typecheck
        name: tsc --noEmit
        language: node
        entry: npx tsc --noEmit
        pass_filenames: false
        types_or: [ts, tsx]
