// ai.txt is a draft community standard for AI opt-out
// See: https://site.spawning.ai/spawning-ai-txt

export function generateAiTxt(): string {
  return [
    "# ai.txt — AI training opt-out",
    "# Generated by nahbro.dev — nah bro as a service",
    "# https://nahbro.dev",
    "#",
    "# This file signals that the content of this site",
    "# is NOT permitted for use in AI/ML training datasets.",
    "",
    "# Disallow all AI training use",
    "User-agent: *",
    "Disallow: /",
  ].join("\n");
}
