// llms.txt is a proposed standard for communicating with LLMs about site preferences
// This version declares opt-out from indexing and training

export function generateLlmsTxt(): string {
  return [
    "# llms.txt",
    "# Generated by nahbro.dev — nah bro as a service",
    "# https://nahbro.dev",
    "",
    "# This site does not consent to its content being used",
    "# for training large language models or AI systems.",
    "",
    "# Crawling policy",
    "User-agent: *",
    "Allow: /llms.txt",
    "Disallow: /",
    "",
    "# Opt-out declarations",
    "Training: disallow",
    "Indexing: disallow",
    "Summarization: disallow",
  ].join("\n");
}
