// Known AI/LLM crawlers as of 2025
// Sources: Dark Visitors, various AI company disclosures
const AI_BOTS = [
  // OpenAI
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  // Anthropic
  "ClaudeBot",
  "Claude-Web",
  "anthropic-ai",
  // Google AI
  "Google-Extended",
  "Googlebot-Extended",
  "Bard",
  // Meta
  "meta-externalagent",
  "FacebookBot",
  // Apple
  "Applebot-Extended",
  // Amazon
  "Amazonbot",
  // Common Crawl / training data
  "CCBot",
  "DataForSeoBot",
  // Bytedance
  "Bytespider",
  // Perplexity
  "PerplexityBot",
  // Cohere
  "cohere-ai",
  // Diffbot
  "Diffbot",
  // AI2 / Allen Institute
  "ai2-unsafe-agent",
  // Scrapers commonly used for AI training
  "ImagesiftBot",
  "omgili",
  "omgilibot",
  "Meltwater",
  // Misc AI agents
  "ia_archiver",
  "YouBot",
  "Timpibot",
  "PetalBot",
  "Kangaroo Bot",
  "SemrushBot-OCOB",
];

export function generateRobotsTxt(): string {
  const lines: string[] = [
    "# Generated by nahbro.dev — nah bro as a service",
    "# Blocks known AI crawlers and LLM training scrapers",
    "# https://nahbro.dev",
    "",
    "# Disallow all AI/LLM crawlers",
    ...AI_BOTS.flatMap((bot) => [`User-agent: ${bot}`, "Disallow: /", ""]),
    "# Allow legitimate crawlers",
    "User-agent: *",
    "Allow: /",
  ];
  return lines.join("
");
}
